theme: jekyll-theme-minimal
title: Gemorion - 科幻风个人网站
description: 科幻美学 · 随笔 · 个人简介 · 知识分享 · 作品集
url: https://hjy-1001.github.io
baseurl: ""
lang: zh-CN
author: Gemorion

# 构建
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

collections:
  essays:
    output: true
    permalink: /essays/:title/
  knowledge:
    output: true
    permalink: /knowledge/:title/
  gallery:
    output: true
    permalink: /gallery/:title/
  about:
    output: true
    permalink: /about/:title/

# 默认布局
defaults:
  - scope:
      path: ""
      type: essays
    values:
      layout: entry
      category: essays
  - scope:
      path: ""
      type: knowledge
    values:
      layout: entry
      category: knowledge
  - scope:
      path: ""
      type: gallery
    values:
      layout: entry
      category: gallery
  - scope:
      path: ""
      type: about
    values:
      layout: entry
      category: about

# 插件（GitHub Pages 白名单）
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# 站点声明（页脚展示）
license_notice: "© 2024 Gemorion · 代码和随笔转载需注明出处；商业用途需联系；艺术作品禁止转载及商业用途"
